---
- hosts: scoldham2.mylabserver.com
  tasks:
    - name: Print disk space
      setup: filter=ansible_mounts
    - debug: var=ansible_mounts.mount
    - name: Print disk space
      shell: "df -k | /usr/bin/grep /dev/xvda2 | /usr/bin/awk {'print $4'}"
      register: disk_info
    - debug: var="disk_info.stdout"
